package com.insis.proposal.cmd.domain;

public enum FormalizationStatus {
    FORMALIZATION_STARTED,
    FORMALIZATION_ACCEPTED_ADVISOR,
    FORMALIZATION_REJECTED_ADVISOR,
    FORMALIZATION_REFACTORED,
    REVIEWERS_REJECTED,
    REVIEWERS_CHOSEN,
    REVIEWERS_ACCEPTED,
    FORMALIZATION_REJECTED,
    FORMALIZATION_ACCEPTED,
    ERROR
}
