spring:
  application:
    name: insis.proposal.cmd
  rabbitmq:
    host: rabbitmq
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
  instance:
    preferIpAddress: true