apiVersion: v1
kind: Service
metadata:
  name: mongo-cmq
  namespace: insis
spec:
  selector:
    app: mongo-cmq
  type: ClusterIP #access: http(s)://<any-cluster-ip>:<svc-port>
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-svc
  namespace: insis
spec:
  selector:
    app: rabbit
  type: NodePort #access: http(s)://<any-cluster-ip>:<svc-port>
  ports:
    - port: 5672
      targetPort: 5672
      name: rabbit-main
    - port: 15672
      targetPort: 15672
      name: rabbit-dash
---
apiVersion: v1
kind: Service
metadata:
  name: cmq
  namespace: insis
spec:
  selector:
    app: cmq
  type: NodePort #access: http(s)://<any-cluster-ip>:<svc-port>
  ports:
    - port: 3000
      targetPort: 3000
      name: cmq
---
apiVersion: v1
kind: Service
metadata:
  name: cmc
  namespace: insis
spec:
  selector:
    app: cmc
  type: NodePort #access: http(s)://<any-cluster-ip>:<svc-port>
  ports:
    - port: 3001
      targetPort: 3001
      name: cmc
---
apiVersion: v1
kind: Service
metadata:
  name: uq-svc
  namespace: insis
spec:
  selector:
    app: uq
  type: NodePort #access: http(s)://<any-cluster-ip>:<svc-port>
  ports:
    - port: 3002
      targetPort: 3002
      name: uq
---
apiVersion: v1
kind: Service
metadata:
  name: uc-svc
  namespace: insis
spec:
  selector:
    app: uc
  type: NodePort #access: http(s)://<any-cluster-ip>:<svc-port>
  ports:
    - port: 3003
      targetPort: 3003
      name: uc
